services:
  - type: web
    name: mijn-website
    env: python
    buildCommand: |
      pyenv global 3.11.9
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
