services:
  - type: web
    name: mijn-website
    env: python
    runtime: python-3.11
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app